version: '3'
services:
  eventstore:
    image: ${DOCKER_USER}/eventstore:${BUILD_VERSION}
    hostname: eventstore
    build:
      dockerfile: Dockerfile
      context: ./services/eventstore
  broker:
    image: ${DOCKER_USER}/broker:${BUILD_VERSION}
    hostname: broker
    build:
      dockerfile: Dockerfile
      context: ./services/broker
  servers:
    image: ${DOCKER_USER}/servers:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - eventstore
    command: sleep 7000 # dotnet ./Adaptive.ReactiveTrader.Server.Launcher.dll config.prod.json --populate-eventstore'
  nginx:
    image: ${DOCKER_USER}/nginx:${BUILD_VERSION}
    hostname: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    ports:
      - '80:80'
  client:
    hostname: client
    build:
      dockerfile: Dockerfile
      context: ./client
  analytics:
    image: ${DOCKER_USER}/analytics:${BUILD_VERSION}
    hostname: analytics
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet ./Adaptive.ReactiveTrader.Server.Analytics.dll config.prod.json'
    depends_on:
      - broker
      - eventstore
  pricing:
    image: ${DOCKER_USER}/pricing:${BUILD_VERSION}
    hostname: pricing
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet ./Adaptive.ReactiveTrader.Server.Pricing.dll config.prod.json'
    depends_on:
      - broker
      - eventstore
      - analytics
  referencedataread:
    image: ${DOCKER_USER}/referencedataread:${BUILD_VERSION}
    hostname: referencedataread
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet ./Adaptive.ReactiveTrader.Server.ReferenceDataRead.dll config.prod.json'
    depends_on:
      - broker
      - eventstore
      - pricing
  tradeexecution:
    image: ${DOCKER_USER}/tradeexecution:${BUILD_VERSION}
    hostname: tradeexecution
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet ./Adaptive.ReactiveTrader.Server.TradeExecution.dll config.prod.json'
    depends_on:
      - broker
      - eventstore
      - referencedataread
  blotter:
    hostname: blotter
    image: ${DOCKER_USER}/blotter:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./server
    command: 'dotnet ./Adaptive.ReactiveTrader.Server.Blotter.dll config.prod.json'
    depends_on:
      - broker
      - eventstore
      - tradeexecution
  pricehistory:
    image: ${DOCKER_USER}/pricehistory:${BUILD_VERSION}
    hostname: pricehistory
    build:
      dockerfile: Dockerfile.dev
      context: ./server/Adaptive.ReactiveTrader.Server.PriceHistory
    depends_on:
      - broker
      - pricing
    environment:
     - BROKER_HOST=broker
     - BROKER_PORT=8000
  nlp:
    image: ${DOCKER_USER}/nlp:${BUILD_VERSION}
    hostname: nlp
    build:
      dockerfile: Nlp.Dockerfile
      context: ./node-server
    depends_on:
      - broker
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=8000
  bot:
    hostname: bot
    image: ${DOCKER_USER}/bot:${BUILD_VERSION}
    build:
      context: ./server/Adaptive.ReactiveTrader.Server.Bot
